#ifndef __REG_BLE_EM_TX_BUFFER_DATA_H_
#define __REG_BLE_EM_TX_BUFFER_DATA_H_

#define REG_BLE_EM_TX_BUFFER_DATA_SIZE 260

#define REG_BLE_EM_TX_BUFFER_DATA_BASE_ADDR 0x00128000


#endif // __REG_BLE_EM_TX_BUFFER_DATA_H_

